config/routes.rb
Rails.application.routes.draw do
  resources :events do
    resources :invites
  end
  
  resources :invites, only: [:show]

  get 'invite/confirm/:token', to: "invites#confirm"
  get 'invite/reject/:token', to: "invites#reject"
  get 'invite/postpone/:token', to: "invites#postpone"

  get 'events/confirm/:id', to: "events#confirm"
  get 'events/duplicate/:id', to: "events#duplicate"

  get 'events/:event_id/guests/new', to: "events#new_guest"
  post 'events/:event_id/guests', to: "events#create_guest"

  get 'invite/info/:token', to: "invites#show_info"
  get 'invite/personalize/:token', to: "invites#edit_info"
  patch 'invite/personalize/:token', to: "invites#update_info"

  get 'sessions/create'
  get 'sessions/destroy'
  get 'home/show'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]

  root to: "events#index"

end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :user
    has_many :invites, :dependent => :destroy
end

app/models/invite.rb
class Invite < ActiveRecord::Base
    UNKNOWN_STATUS = 0
    CONFIRMED_STATUS = 1
    REJECTED_STATUS = 2
    POSTPONED_STATUS = 3

    has_secure_token
    belongs_to :event
end

# add_column :invites, :receive_emails, :boolean, defualt: 1, null: false
# add_column :invites, :token, :string
# create_table :invites do |t|
#       t.string :mail
#       t.integer :confirmed
#       t.string :name
#       t.references :event, index: true, foreign_key: true

#       t.timestamps null: false
#     end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :events
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(Hash["name" => event_params['name'], "user_id" => current_user.id])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def confirm
    @event = Event.find(params[:id])
    @event.invites.each do |invite|
      ExampleMailer.sample_email(invite).deliver_later
    end
    flash[:notice] = 'Evento confirmado, mails preparados'
    redirect_to event_path(@event)
  end

  # GET /events/1/guests/new
  def new_guest
    @event = Event.find(params[:event_id])
  end

  # POST /events/1/guests
  def create_guest
    @event = Event.find(params[:event_id])
    @invite = @event.invites.create(Hash[
      "name" => guest_params['name'],
      "mail" => guest_params['mail'],
      "invite_type" => 'guest',
      "confirmed" => 1,
      "receive_emails" => false
    ])
    send_update_emails(@event)
    flash[:notice] = "Guest #{ guest_params['name'] } agregado!"
    redirect_to event_path(@event)
  end

  # GET /events/1/duplicate
  def duplicate
    event = Event.find(params[:id])
    new_event = event.dup
    new_event.save()
    event.invites.where(invite_type: 'invite').each do |invite|
      new_invite = invite.dup
      new_invite.event = new_event
      new_invite.confirmed = Invite::UNKNOWN_STATUS
      new_invite.receive_emails = true
      new_invite.regenerate_token
      new_invite.save
    end
    redirect_to event_path(new_event)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :user_id)
    end

    def guest_params
      params.require(:guest).permit(:name, :mail)
    end

    def send_update_emails(event)
      event.invites.where(receive_emails: true).each do |invite|
        ConfirmedMailer.sample_email(invite).deliver_later
      end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
    before_action :set_invite, only: [:show]
    before_action :set_invite_by_token, only: [:confirm, :reject, :postpone, :show_info, :edit_info, :update_info]

    def create
        @event = Event.find(params[:event_id])
        @invite = @event.invites.create(Hash[
            "name" => invite_params['name'],
            "mail" => invite_params['mail'],
            "confirmed" => 0,
            "receive_emails" => true
        ])
        if (params[:send_email])
            ExampleMailer.sample_email(@invite).deliver_later
        end
        flash[:notice] = 'Invite agregado'
        redirect_to event_path(@event)
    end

    def show
    end

    def confirm
        @invite.confirmed = Invite::CONFIRMED_STATUS
        if @invite.save
            send_emails @invite
            render :confirmed, layout: false
        end
    end

    def reject
        @invite.confirmed = Invite::REJECTED_STATUS
        if @invite.save
            send_emails @invite
            render :rejected, layout: false 
        end
    end

    def postpone
        @invite.confirmed = Invite::POSTPONED_STATUS
        if @invite.save
            send_emails @invite
            render :postponed, layout: false
        end
    end

    def show_info
    end

    def edit_info
    end

    def update_info
        if @invite.update(invite_update_info_params)
            redirect_to({ action: 'show_info' }, notice: "Se actualizaron los datos.")
        else
            render :edit_info
        end
    end

    private
        # Use callbacks to share common setup or constraints between actions.
        def set_invite
            @invite = Invite.find(params[:id])
        end

        def set_invite_by_token
            @invite = Invite.find_by(token: params[:token])
        end

        def invite_params
            params.require(:invite).permit(:name, :mail)
        end

        def invite_update_info_params
            # params.require(:invite).permit(:name, :receive_emails, :confirmed)
            params.require(:invite).permit(:name, :receive_emails)
        end

        def send_emails(invite)
              invite.event.invites.where(receive_emails: true).each do |invite|
                ConfirmedMailer.sample_email(invite).deliver_later
            end
        end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/_invites_event.html.erb
<h4>invites</h4>
<table>
	<thead>
		<td>
			nombre
		</td>
		<td>
			mail
		</td>
		<td>
			status
		</td>
		<td>
			accion
		</td>
	</thead>
	<tbody>
		<% @event.invites.each do |invite| %>
			<tr>
				<td>
					<%= invite.name %>	
				</td>
				<td>
					<%= invite.mail %>	
				</td>
				<td>
					<%= invite.confirmed %>	
				</td>
				<td>
					acciones
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

<!-- <h5>Add an invite</h5>

<%= form_for([@event, @event.invites.build]) do |f|%>
	<p>
		<%= f.label :name %> <br />
		<%= f.text_field :name %> <br />
	</p>
	<p>
		<%= f.label :mail %> <br />
		<%= f.text_field :mail %> <br />
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %> -->

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/guest.html.erb
<div>
  <p id="notice"><%= notice %></p>
  <p>
    Agregar invitado.
  </p>
  <br><br>
  <%= form_tag(controller: "events", action: "create_guest", id: @event.id,method: "post") do %>
    <%= label_tag(:name, "Nombre del invitado:") %>
    <%= text_field_tag 'guest[name]', nil, :required => true %>
    <%= label_tag(:mail, "Email del invitado:") %>
    <%= email_field 'guest', :mail, :required => true %>
    <%= submit_tag("Agregar") %>
  <% end %>
</div>

app/views/events/index.html.erb
  <div class="section no-pad-bot" id="index-banner">
  <div class="container">
    <p id="notice"><%= notice %></p>


    <% unless current_user.nil? %>

      <h1>Listing Events</h1>

      <table>
        <thead>
          <tr>
            <th>Name  <%= @token %></th>
            <th>User</th>
            <th colspan="4">Acciones</th>
          </tr>
        </thead>

        <tbody>
          <% current_user.events.each do |event| %>
            <tr>
              <td><%= event.name %></td>
              <td><%= event.user_id %></td>

              <td><%= link_to 'Show', event %></td>
              <td><%= link_to 'Edit', edit_event_path(event) %></td>
              <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <td><%= link_to 'Duplicate', { controller: "events", action: "duplicate", id: event.id }, data: { confirm: 'Queres duplicar?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Event', new_event_path %>
    <% end %>
  </div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/new_guest.html.erb
<div>
  <p id="notice"><%= notice %></p>
  <p>
    Agregar invitado.
  </p>
  <br><br>
  <%= form_tag(controller: "events", action: "create_guest", id: @event.id,method: "post") do %>
    <%= label_tag(:name, "Nombre del invitado (obligatorio):") %>
    <%= text_field_tag 'guest[name]', nil, :required => true %>
    <%= label_tag(:mail, "Email del invitado (opcional):") %>
    <%= email_field 'guest', :mail, :required => false %>
    <%= submit_tag("Agregar") %>
  <% end %>
</div>

app/views/events/show.html.erb
<h5 id="notice"><%= notice %></h5>

<h4>Event</h4>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @event.user.name %>
</p>

<% unless @event.invites.count < 1 %>
	<%= render 'invites_event' %>
<% end %>

<br><br>

<h5>Add an invite</h5>

<%= form_for([@event, @event.invites.build]) do |f|%>
    <p>
        <%= f.label :name %> <br />
        <%= f.text_field :name %> <br />
    </p>
    <p>
        <%= f.label :mail %> <br />
        <%= f.text_field :mail %> <br />
    </p>
    <p>
        <%= check_box_tag(:send_email) %>
        <%= label_tag(:send_email, "Enviar email?") %>
    </p>
    <p>
        <%= f.submit %>
    </p>
<% end %>

<br><br>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %> |
 <a href="<%=url_for(host: ENV['URL_FOR_HOST'], controller: 'events', action: 'confirm') %>">confirm </a> |
 <a href="<%=url_for(host: ENV['URL_FOR_HOST'], controller: 'events', action: 'duplicate') %>">duplicate</a>

app/views/home/show.html.erb
<%# <h1>Home#show</h1>
<p>Find me in app/views/home/show.html.erb</p> %>


<h2>Eventos</h2>

<table>
	<thead>
		<tr>
			<td>
				Evento
			</td>
			<td>
				Fecha de envio
			</td>
			<td>
				Fecha de creacion
			</td>
			<td>
				Acciones
			</td>
		</tr>
		
	</thead>
	<tbody>
		<tr>
			<td>
				Evento 1
			</td>
			<td>
				15/10/2016
			</td>
			<td>
				15/10/2016
			</td>
			<td>
				editar
			</td>
		</tr>
		<tr>
			<td>
				Evento 2 
			</td>
			<td>
				15/10/2016
			</td>
			<td>
				15/10/2016
			</td>
			<td>
				editar
			</td>
		</tr>
	</tbody>
</table>

app/views/invites/_edit_profile.html.erb
<p>
        <a href="<%= url_for(host: ENV['URL_FOR_HOST'],
                  controller: 'invites',
                  action: 'edit_info',
                  token: @invite.token) %>"><button>Editar perfil</button></a>
      </p>

app/views/invites/confirmed.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>rubyfutbol</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div>
      <p id="notice"><%= notice %></p>
      <p>
        Su asistencia al evento <b><%= @invite.event.name %></b> ha sido <u>confirmada</u>
      </p>
      <p>
        Muchas gracias!
      </p>
      <br>
      <%= render "edit_profile" %>
    </div>

    <div id='masche' style="display:none;">
     <img width="320px" height="180px" src="http://generadordememesonline.com/media/created/0vgxnt.jpg">
    </div>
  </body>
</html>

app/views/invites/edit_info.html.erb
<div>
  <p id="notice"><%= notice %></p>
  <p>
    Editar info de <b><%= @invite.name %></b>
  </p>
  <br><br>

  <%= form_for @invite, url: {action: "update_info"} do |f| %>
  <div class="field">
    <%= f.label :name, "Nombre" %><br>
    <%= f.text_field :name %>
  </div>
  <!-- <div class="field">
    <%= f.label :confirmed, "Estatus" %><br>
    <%= f.select(:confirmed, [['Asistire', 1], ['No asisitre', 2]]) %>
  </div> -->
  <br>
  <div class="field">
    <%= f.check_box :receive_emails %>
    <%= f.label :receive_emails, "Recibir emails?" %>
  </div>
  <br><br>
  <div class="actions">
    <%= f.submit 'Guardar' %>
  </div>
<% end %>

</div>

<script>
  $(document).ready(function() {
    $('select').material_select();
  });
</script>

app/views/invites/postponed.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>rubyfutbol</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div>
      <p id="notice"><%= notice %></p>
      <p>
        Se te <u>recordara en 2 dias</u> del evento: <b><%= @invite.event.name %>
      </p>
      <p>
        Muchas gracias!
      </p>
    </div>
  </body>
</html>

app/views/invites/rejected.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>rubyfutbol</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div>
      <p id="notice"><%= notice %></p>
      <p>
        Has <u>rechazado</u> la invitacion al evento: <b><%= @invite.event.name %></b>
      </p>
      <p>
        Muchas gracias!
      </p>
      <br>
      <%= render "edit_profile" %>
    </div>
  </body>
</html>

app/views/invites/show.html.erb
<p id="notice"><%= notice %></p>

<h4>Invite</h4>

<p>
  <strong>id:</strong>
  <%= @invite.id %>
</p>

<p>
  <strong>mail:</strong>
  <%= @invite.mail %>
</p>

<p>
  <strong>confirmed:</strong>
  <%= @invite.confirmed %>
</p>

<p>
  <strong>Name:</strong>
  <%= @invite.name %>
</p>

<p>
  <strong>event_id:</strong>
  <%= @invite.event_id %>
</p>

app/views/invites/show_info.html.erb
<p id="notice"><%= notice %></p>

<h4>Info de tu invitacion</h4>

<p>
  <strong>Name:</strong>
  <%= @invite.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @invite.mail %>
</p>

<p>
  <strong>Evento:</strong>
  <%= @invite.event.name %>
</p>

<p>
  <strong>Estatus:</strong>
  <% if @invite.confirmed === 1 %>
    Asistira
  <% elsif @invite.confirmed === 2 %>
    No asistira
  <% else %>
    Sin confirmar
  <% end %>
</p>


<p>
  <strong>Recibe updates?:</strong>
  <% if @invite.receive_emails === true %>
    Si
  <% else %>
    No
  <% end %>
</p>

<%= link_to 'Editar info', controller: "invites", action: "edit_info", token: @invite.token %>

app/views/invites/status.html.erb
<h4>Su invitación ha sido </h4>

app/views/invites/update_info.html.erb
<div>
    <p id="notice"><%= notice %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>rubyfutbol</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    
    <nav class="light-blue lighten-1" role="navigation">
      <div>
        <% if current_user %>
          Signed in as <strong><%= current_user.name %></strong>!
          <%= link_to "Sign out", signout_path, id: "sign_out" %>
        <% else %>
          <%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %>
          <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
        <% end %>
        </div>
    </nav>
    <div class="section no-pad-bot" id="index-banner">
     <div class="container">
      <%= yield %>
     </div>
    </div>
    <footer class="page-footer orange">
      <div class="container">
        <div class="row">
          <div class="col l6 s12">
            <p class="grey-text text-lighten-4"></p>
          </div>
          <div class="col l3 s12">
           
          </div>
          <div class="col l3 s12">
           
          </div>
        </div>
      </div>
      <div class="footer-copyright">
        <div class="container">
        </div>
      </div>
    </footer>
  </body>
</html>